name: Deploy

# triggers
on:
  push:
    branches:
      - main

# jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install project dependencies
        run: npm install

      - name: Start JSON server and React app
        run: npm start